name: workflow
on:
  push:
    branches:
      - segunda-rama

jobs:
  sast:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout code 
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      
      - name: set environment variables
        run: echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: validate and configure package-lock.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        run: | 
          if [ -f "package-lock.json" ]; then
            echo "encontro el archivo"
            echo "verificando configuracion del plugin sonar"
            if ! grep -q 'id "org.sonarqube"  version "3.3"' package-lock.json; then
              sed -i '/id \'java\'/a \ \ \ \ id \'org.sonarqube\' version \'3.3\'' package-lock.json
              echo "plugin de sonarcloud a√±adido a package-lock.json"

          else
            echo "plugin de sonarcloud ya esta configurado en package-lock.json"
          fi


          else
            echo "no se encontro archivo package-lock.json"
            exit 1
          fi


    